# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target '29th-iOS-week4-homework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 29th-iOS-week4-homework
  pod 'Alamofire', '~> 5.4'

end

